### ISSUE TITLE
Lock file and config file

### ISSUE THREAD

**Issue by omirobarcelo** [chibat/heroku-deno-getting-started#5]
The web command in the Procfile is:  
`web: deno run --allow-net=:${PORT} --cached-only main.ts --port=${PORT}`.

What if we have a `lock.json` and a `tsconfig.json`? Does this work?  
`web: deno run --allow-net=:${PORT} --cached-only --lock=lock.json -c tsconfig.json main.ts --port=${PORT}`

**Comment by chibat** [comment]
I tried it.
I think you can use `--config` and `--lock`.
However, I found a buildpack error display that can be ignored.
I fixed it.

Thanks for your report !
